"""Block Kit formatting for proactive alerts."""
from formatters.helpers import timestamp, format_currency


def format_alerts_digest(
    alerts: list,
    total_pipeline_value: float,
) -> tuple[list, str]:
    """Format a digest of all current alerts as Block Kit.

    Args:
        alerts: List of dicts with 'type', 'emoji', 'title', 'detail', 'deal_name', 'amount'
        total_pipeline_value: Total value of open pipeline

    Returns:
        tuple: (blocks, fallback_text)
    """
    if not alerts:
        blocks = [
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": "✅ *All clear!* No pipeline alerts right now. Keep up the great work."}
            },
            {
                "type": "context",
                "elements": [
                    {"type": "mrkdwn", "text": f"Pipeline: {format_currency(total_pipeline_value)} • {timestamp()}"}
                ]
            },
        ]
        return blocks, "No pipeline alerts."

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"🔔 Pipeline Alerts ({len(alerts)})", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"📊 Alerts checked {timestamp()} · Monitoring last 48 hours of activity · Pipeline: {format_currency(total_pipeline_value)}"}
            ]
        },

        {"type": "divider"},
    ]

    for i, alert in enumerate(alerts[:8]):
        emoji = alert.get("emoji", "⚠️")
        title = alert.get("title", "Alert")
        detail = alert.get("detail", "")
        deal_name = alert.get("deal_name", "")
        amount = alert.get("amount", 0)

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"{emoji} *{title}*\n{detail}\n_{format_currency(amount)}_"
            },
            "accessory": {
                "type": "button",
                "text": {"type": "plain_text", "text": "View Deal", "emoji": True},
                "action_id": f"alert_view_deal",
                "value": deal_name,
            }
        })

        if i < len(alerts) - 1:
            blocks.append({"type": "divider"})

    blocks.append({"type": "divider"})
    blocks.append({
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "📈 View Pipeline", "emoji": True},
                "action_id": "refresh_pipeline",
                "value": "refresh",
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "📬 View Follow-Ups", "emoji": True},
                "action_id": "home_followups",
                "value": "followups",
            },
        ]
    })

    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • Proactive Alerts • {timestamp()}"}
        ]
    })

    # Rich fallback for screen readers
    alert_summaries = "; ".join([f"{a.get('title', 'Alert')}: {a.get('deal_name', 'Unknown')}" for a in alerts[:5]])
    fallback = f"Pipeline Alerts: {len(alerts)} items need attention. {alert_summaries}"
    return blocks, fallback


def format_single_alert(
    emoji: str,
    title: str,
    detail: str,
    deal_name: str,
    amount: float,
) -> tuple[list, str]:
    """Format a single proactive alert for DM delivery.

    Returns:
        tuple: (blocks, fallback_text)
    """
    blocks = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"{emoji} *{title}*\n{detail}"
            },
            "accessory": {
                "type": "button",
                "text": {"type": "plain_text", "text": "Open Deal", "emoji": True},
                "action_id": "alert_view_deal",
                "value": deal_name,
            }
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"SalesCoach AI • {timestamp()}"}
            ]
        },
    ]

    fallback = f"{emoji} {title}: {detail}"
    return blocks, fallback
