"""Block Kit formatting for /competitor command."""
from formatters.helpers import timestamp, truncate


def format_competitor_response(
    competitor_name: str,
    positioning: str,
    strengths_weaknesses: dict,
    counter_arguments: list,
    recent_news: list,
    deals_at_risk: list,
    talking_points: str,
) -> tuple[list, str]:
    """Format a competitive intelligence brief as Block Kit.

    Args:
        competitor_name: Name of the competitor
        positioning: LLM-generated positioning statement
        strengths_weaknesses: Dict with 'strengths' and 'weaknesses' lists
        counter_arguments: List of dicts with 'objection' and 'response'
        recent_news: List of dicts with 'title', 'summary', 'url'
        deals_at_risk: List of dicts with 'deal_name', 'stage', 'amount'
        talking_points: LLM-generated talking points string

    Returns:
        tuple: (blocks, fallback_text)
    """
    # Strengths & weaknesses
    strengths = strengths_weaknesses.get("strengths", [])
    weaknesses = strengths_weaknesses.get("weaknesses", [])
    strengths_str = "\n".join([f"• {s}" for s in strengths[:5]]) if strengths else "_Unknown_"
    weaknesses_str = "\n".join([f"• {w}" for w in weaknesses[:5]]) if weaknesses else "_Unknown_"

    # Counter-arguments
    if counter_arguments:
        counter_str = "\n".join([
            f"• *\"{c.get('objection', '')}\"*\n  -> {c.get('response', '')}"
            for c in counter_arguments[:5]
        ])
    else:
        counter_str = "_No specific counter-arguments — try `/objection [concern]` for general rebuttals_"

    # Recent news
    if recent_news:
        news_str = "\n".join([
            f"• *{truncate(n.get('title', ''), 80)}*\n  {truncate(n.get('summary', ''), 150)}"
            for n in recent_news[:4]
        ])
    else:
        news_str = "_No recent news found — check back later_"

    # Deals at risk
    if deals_at_risk:
        risk_str = "\n".join([
            f"• *{d.get('deal_name', 'Unknown')}* — {d.get('stage', 'N/A')} — ${int(float(d.get('amount', 0) or 0)):,}"
            for d in deals_at_risk[:5]
        ])
    else:
        risk_str = "_No active deals mentioning this competitor_"

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"Competitive Intel: {competitor_name}", "emoji": True}
        },

        # Positioning
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Our Positioning:*\n{positioning or '_Not available_'}"}
        },

        {"type": "divider"},

        # Two-column: Their Strengths vs Their Weaknesses
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Their Strengths:*\n{strengths_str}"},
                {"type": "mrkdwn", "text": f"*Their Weaknesses:*\n{weaknesses_str}"},
            ]
        },

        {"type": "divider"},

        # Counter-arguments
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*When They Say -> You Say:*\n{counter_str}"}
        },

        {"type": "divider"},

        # Recent news
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Recent News (Last 30 Days):*\n{news_str}"}
        },

        {"type": "divider"},

        # Deals at risk
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Your Deals Mentioning {competitor_name}:*\n{risk_str}"}
        },

        {"type": "divider"},

        # Talking points
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Talking Points for Your Next Call:*\n{talking_points or '_Not available_'}"}
        },

        # Action buttons
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Start Roleplay vs This Competitor", "emoji": True},
                    "action_id": "roleplay_competitor",
                    "value": competitor_name or "competitor",
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Draft Competitive Email", "emoji": True},
                    "action_id": "draft_competitive_email",
                    "value": competitor_name or "competitor",
                },
            ]
        },

        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • Battle Cards + Live Search • {timestamp()}"}
            ]
        },
    ]

    # Rich fallback for screen readers
    strengths_list = ", ".join(strengths[:3]) if strengths else "Unknown"
    weaknesses_list = ", ".join(weaknesses[:3]) if weaknesses else "Unknown"
    fallback = f"Competitive Intel for {competitor_name}. Positioning: {positioning[:100] if positioning else 'N/A'}. Their strengths: {strengths_list}. Their weaknesses: {weaknesses_list}. {len(deals_at_risk)} deals at risk."
    return blocks, fallback
