"""Block Kit formatting for /email-sequence command."""
from formatters.helpers import timestamp, truncate


def format_email_sequence_response(
    company_name: str,
    sequence_type: str,
    emails: list,
    contact_name: str,
    contact_email: str,
) -> tuple[list, str]:
    """Format a multi-touch email sequence as Block Kit.

    Args:
        company_name: Target company
        sequence_type: Type of sequence (post-demo, cold-outreach, re-engagement, etc.)
        emails: List of dicts with 'day', 'subject', 'body', 'cta', 'angle'
        contact_name: Recipient name
        contact_email: Recipient email

    Returns:
        tuple: (blocks, fallback_text)
    """
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"📧 Email Sequence: {company_name}", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Type: {sequence_type.title()} • To: {contact_name} ({contact_email}) • {len(emails)} emails • {timestamp()}"}
            ]
        },

        {"type": "divider"},
    ]

    for i, email in enumerate(emails):
        day = email.get("day", f"Day {i+1}")
        subject = email.get("subject", "No subject")
        body = email.get("body", "")
        angle = email.get("angle", "")

        # Email card
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*Email {i+1} — {day}*\n"
                    f"_{angle}_\n\n"
                    f"*Subject:* {subject}\n\n"
                    f"{truncate(body, 800)}"
                )
            }
        })

        # Action buttons per email
        blocks.append({
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": f"📋 Copy Email {i+1}", "emoji": True},
                    "action_id": f"copy_sequence_email_{i}",
                    "value": f"{company_name}||{i}",
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": f"✏️ Refine", "emoji": True},
                    "action_id": f"refine_sequence_email_{i}",
                    "value": f"{company_name}||{i}",
                },
            ]
        })

        if i < len(emails) - 1:
            blocks.append({"type": "divider"})

    # Footer
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "🔄 Regenerate All", "emoji": True},
                "action_id": "regenerate_email_sequence",
                "value": f"{company_name}||{sequence_type}",
            },
        ]
    })

    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • Email Sequence • {timestamp()}"}
        ]
    })

    # Rich fallback for screen readers
    email_subjects = "; ".join([f"Email {i+1}: {e.get('subject', 'No subject')}" for i, e in enumerate(emails[:4])])
    fallback = f"Email Sequence for {company_name}. Type: {sequence_type}. To: {contact_name} ({contact_email}). {len(emails)} emails: {email_subjects}"
    return blocks, fallback
