"""Block Kit formatting for /followup command."""
import json
from formatters.helpers import timestamp, format_currency, truncate


def format_followup_response(
    followup_items: list,
    total_count: int,
) -> tuple[list, str]:
    """Format a follow-up action list as Block Kit.

    Args:
        followup_items: List of dicts, each with:
            - deal_name: str
            - company: str
            - urgency: "high" | "medium" | "low"
            - reason: str (why follow-up is needed)
            - last_activity: str (date + summary of last touch)
            - suggested_action: str (LLM-generated specific action)
            - draft_snippet: str (LLM-generated 1-line email opener)
        total_count: Total number of deals needing follow-up

    Returns:
        tuple: (blocks, fallback_text)
    """
    urgency_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "Follow-Up Actions", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Found *{total_count}* deals needing follow-up. Prioritized by urgency."}
            ]
        },
        {"type": "divider"},
    ]

    for i, item in enumerate(followup_items[:10]):  # Max 10 to stay under block limit
        emoji = urgency_emoji.get(item.get("urgency", "medium"), "🟡")
        deal_name = item.get("deal_name", "Unknown Deal")
        company = item.get("company", "")
        reason = item.get("reason", "")
        last_activity = item.get("last_activity", "N/A")
        suggested_action = item.get("suggested_action", "Follow up")
        draft_snippet = truncate(item.get("draft_snippet", ""), 100)

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"{emoji} *{deal_name}*"
                    + (f" ({company})" if company else "")
                    + f"\n{reason}"
                    + f"\n_Last touch: {last_activity}_"
                    + f"\n*Suggested:* {suggested_action}"
                    + (f"\n_{draft_snippet}_" if draft_snippet else "")
                ),
            },
            "accessory": {
                "type": "button",
                "text": {"type": "plain_text", "text": "Draft Email", "emoji": True},
                "action_id": "draft_followup_email",
                "value": json.dumps({
                    "deal_name": deal_name,
                    "company": company or deal_name,
                    "context": reason,
                }),
            }
        })

    if total_count > 10:
        blocks.append({
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"_Showing top 10 of {total_count} deals. Use `/followup [company]` for specific ones._"}
            ]
        })

    blocks.append({"type": "divider"})
    blocks.append({
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "Refresh", "emoji": True},
                "action_id": "refresh_followups",
                "value": "refresh",
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "View Pipeline", "emoji": True},
                "action_id": "refresh_pipeline",
                "value": "refresh",
            },
        ]
    })

    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • {timestamp()}"}
        ]
    })

    # Rich fallback for screen readers
    deal_summaries = "; ".join([f"{item.get('deal_name', 'Unknown')}: {item.get('reason', 'needs follow-up')}" for item in followup_items[:5]])
    fallback = f"Follow-Up Actions: {total_count} deals need attention. {deal_summaries}"
    return blocks, fallback
