"""Block Kit formatting for /forecast command."""
from formatters.helpers import timestamp, format_currency


def format_forecast_response(
    committed: float,
    best_case: float,
    worst_case: float,
    stage_breakdown: list,
    risk_flags: list,
    insights: str,
    period: str,
) -> tuple[list, str]:
    """Format a pipeline forecast as Block Kit.

    Args:
        committed: Weighted forecast (most likely)
        best_case: If all deals close
        worst_case: Only high-confidence deals
        stage_breakdown: List of dicts with 'stage', 'count', 'value', 'weighted'
        risk_flags: List of dicts with 'deal_name', 'reason', 'amount'
        insights: LLM-generated narrative analysis
        period: Forecast period label (e.g., "March 2026")

    Returns:
        tuple: (blocks, fallback_text)
    """
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"📊 Pipeline Forecast — {period}", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"📊 Forecast as of {timestamp()} · Based on current pipeline data"}
            ]
        },

        {"type": "divider"},

        # Three scenarios
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*🎯 Committed:*\n{format_currency(committed)}"},
                {"type": "mrkdwn", "text": f"*🚀 Best Case:*\n{format_currency(best_case)}"},
                {"type": "mrkdwn", "text": f"*⚠️ Worst Case:*\n{format_currency(worst_case)}"},
                {"type": "mrkdwn", "text": f"*📈 Pipeline Coverage:*\n{best_case / committed:.1f}x" if committed > 0 else "*📈 Pipeline Coverage:*\nN/A"},
            ]
        },

        {"type": "divider"},
    ]

    # Stage breakdown
    if stage_breakdown:
        stage_text = ""
        for s in stage_breakdown:
            stage_text += f"• *{s['stage']}:* {s['count']} deals — {format_currency(s['value'])} → weighted: {format_currency(s['weighted'])}\n"

        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*📋 By Stage:*\n{stage_text}"}
        })
        blocks.append({"type": "divider"})

    # Risk flags
    if risk_flags:
        risk_text = ""
        for r in risk_flags[:5]:
            risk_text += f"• 🚨 *{r['deal_name']}* ({format_currency(r['amount'])}) — {r['reason']}\n"

        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*⚠️ Forecast Risks:*\n{risk_text}"}
        })
        blocks.append({"type": "divider"})

    # AI insights
    if insights:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*🧠 AI Analysis:*\n{insights}"}
        })

    # Action buttons
    blocks.append({
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "View Pipeline", "emoji": True},
                "action_id": "refresh_pipeline",
                "value": "refresh",
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "View At-Risk Deals", "emoji": True},
                "action_id": "forecast_at_risk",
                "value": "at_risk",
            },
        ]
    })

    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • Pipeline Forecast • {timestamp()}"}
        ]
    })

    # Rich fallback for screen readers
    risk_summary = ", ".join([r['deal_name'] for r in risk_flags[:3]]) if risk_flags else "None"
    fallback = f"Pipeline Forecast for {period}. Committed: {format_currency(committed)}. Best case: {format_currency(best_case)}. Worst case: {format_currency(worst_case)}. {len(risk_flags)} at-risk deals: {risk_summary}. {insights[:100] if insights else 'No additional insights'}..."
    return blocks, fallback
