"""Block Kit formatting for /objection command."""
from formatters.helpers import timestamp


def format_objection_response(
    objection: str,
    response_script: str,
    proof_points: list,
    avoid: list,
    follow_up_question: str,
) -> tuple[list, str]:
    """Format an objection handling response as Block Kit.

    Args:
        objection: The original objection text
        response_script: LLM-generated response the rep can use verbatim
        proof_points: List of supporting data points / case study references
        avoid: List of things NOT to say
        follow_up_question: A question to pivot the conversation

    Returns:
        tuple: (blocks, fallback_text)
    """
    # Proof points
    if proof_points:
        proof_str = "\n".join([f"• {p}" for p in proof_points[:4]])
    else:
        proof_str = "_No specific proof points available_"

    # What to avoid
    if avoid:
        avoid_str = "\n".join([f"• {a}" for a in avoid[:3]])
    else:
        avoid_str = "_No specific warnings_"

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "Objection Response", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"They said: _{objection}_"}
            ]
        },

        {"type": "divider"},

        # The response to use — this is the star of the show
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Say This:*\n\n{response_script}"
            }
        },

        {"type": "divider"},

        # Two columns: proof points and what to avoid
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Proof Points:*\n{proof_str}"},
                {"type": "mrkdwn", "text": f"*Avoid Saying:*\n{avoid_str}"},
            ]
        },

        {"type": "divider"},

        # Follow-up question to pivot
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Pivot With:*\n_{follow_up_question}_"
            }
        },

        # Action buttons with overflow for secondary actions
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Practice This Objection", "emoji": True},
                    "action_id": "practice_objection",
                    "value": objection or "objection",
                    "style": "primary",
                },
                {
                    "type": "overflow",
                    "action_id": "objection_overflow",
                    "options": [
                        {
                            "text": {"type": "plain_text", "text": "Get Full Objection Guide"},
                            "value": f"expand_objection|{objection or 'objection'}",
                        },
                        {
                            "text": {"type": "plain_text", "text": "Save to Playbook"},
                            "value": f"save_objection|{objection or 'objection'}",
                        },
                    ],
                },
            ]
        },

        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • Objection Playbook • {timestamp()}"}
            ]
        },
    ]

    # Rich fallback for screen readers
    fallback = f"Objection Response for '{objection}'. Response script: {response_script[:200]}... Proof points: {', '.join(proof_points[:3]) if proof_points else 'None'}. Follow-up question: {follow_up_question}"
    return blocks, fallback
