"""Block Kit formatting for /persona command."""
from formatters.helpers import timestamp, truncate


def format_persona_response(
    company_name: str,
    persona_name: str,
    persona_title: str,
    persona_profile: dict,
    messaging_guide: dict,
    conversation_starters: list,
) -> tuple[list, str]:
    """Format a buyer persona as Block Kit.

    Args:
        company_name: Company name
        persona_name: Contact name (or "Typical [Title]" if no specific contact)
        persona_title: Job title
        persona_profile: Dict with 'background', 'pain_points', 'priorities', 'decision_style', 'communication_pref'
        messaging_guide: Dict with 'do', 'dont', 'value_props'
        conversation_starters: List of opening questions/topics

    Returns:
        tuple: (blocks, fallback_text)
    """
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"👤 Buyer Persona: {persona_title}", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"{persona_name} at {company_name} • {timestamp()}"}
            ]
        },

        {"type": "divider"},

        # Background
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*📋 Background:*\n{truncate(persona_profile.get('background', 'N/A'), 500)}"
            }
        },

        {"type": "divider"},

        # Pain points and priorities
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*🎯 Pain Points:*\n{chr(10).join(['• ' + p for p in persona_profile.get('pain_points', [])[:4]])}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*📌 Priorities:*\n{chr(10).join(['• ' + p for p in persona_profile.get('priorities', [])[:4]])}"
                },
            ]
        },

        # Decision style and communication
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*🧠 Decision Style:*\n{persona_profile.get('decision_style', 'N/A')}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*💬 Communication:*\n{persona_profile.get('communication_pref', 'N/A')}"
                },
            ]
        },

        {"type": "divider"},

        # Messaging dos and don'ts
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*✅ Do:*\n{chr(10).join(['• ' + d for d in messaging_guide.get('do', [])[:4]])}"
                },
                {
                    "type": "mrkdwn",
                    "text": f"*❌ Don't:*\n{chr(10).join(['• ' + d for d in messaging_guide.get('dont', [])[:4]])}"
                },
            ]
        },

        {"type": "divider"},
    ]

    # Value props
    if messaging_guide.get("value_props"):
        vp_text = "\n".join([f"• 💎 {v}" for v in messaging_guide["value_props"][:3]])
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Value Props That Resonate:*\n{vp_text}"}
        })

    # Conversation starters
    if conversation_starters:
        starters_text = "\n".join([f"• 💬 _{s}_" for s in conversation_starters[:4]])
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Conversation Starters:*\n{starters_text}"}
        })

    # Action buttons
    blocks.append({"type": "divider"})
    blocks.append({
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "Draft Email", "emoji": True},
                "action_id": "draft_email_from_persona",
                "value": f"{company_name}||{persona_name}",
            },
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "Practice Call", "emoji": True},
                "action_id": "roleplay_from_persona",
                "value": f"{company_name}||{persona_title}",
            },
        ]
    })

    blocks.append({
        "type": "context",
        "elements": [
            {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • Buyer Persona • {timestamp()}"}
        ]
    })

    # Rich fallback for screen readers
    pain_points = ", ".join(persona_profile.get('pain_points', [])[:3]) if persona_profile.get('pain_points') else "Not specified"
    priorities = ", ".join(persona_profile.get('priorities', [])[:3]) if persona_profile.get('priorities') else "Not specified"
    fallback = f"Buyer Persona for {persona_name}, {persona_title} at {company_name}. Pain points: {pain_points}. Priorities: {priorities}. Decision style: {persona_profile.get('decision_style', 'N/A')}."
    return blocks, fallback
