"""Block Kit formatting for /pipeline command."""
from formatters.helpers import timestamp, format_currency


def format_pipeline_response(
    total_value: float,
    deal_count: int,
    weighted_forecast: float,
    deals_by_stage: list,
    flagged_deals: list,
    recommendations: list,
) -> tuple[list, str]:
    """Format a pipeline health digest as Block Kit.

    Args:
        deals_by_stage: List of tuples (stage_name, count, value)
        flagged_deals: List of dicts with 'id', 'name', 'flag', 'reason'
        recommendations: List of recommendation strings

    Returns:
        tuple: (blocks, fallback_text)
    """
    # Build stage breakdown as monospace table
    if deals_by_stage:
        stage_str = "```\n"
        stage_str += "Stage           | Deals | Value\n"
        stage_str += "----------------+-------+------------\n"
        for stage, count, value in deals_by_stage:
            stage_col = stage[:15].ljust(15)
            count_col = str(count).center(5)
            value_col = format_currency(value).rjust(10)
            stage_str += f"{stage_col} | {count_col} | {value_col}\n"
        stage_str += "```"
    else:
        stage_str = "_No deals in pipeline yet — add deals in HubSpot to get started_"

    # Build flagged deals with risk type (limit to 3 for compact display)
    MAX_FLAGGED_DISPLAY = 3
    flag_emoji = {"stale": "⏰", "overdue": "🚨", "at_risk": "⚠️"}
    if flagged_deals:
        displayed_flagged = flagged_deals[:MAX_FLAGGED_DISPLAY]
        flagged_str = "\n".join([
            f"• {flag_emoji.get(d.get('flag', 'at_risk'), '⚠️')} *{d.get('name', 'Unknown')}* — {d.get('reason', 'Flagged')}"
            for d in displayed_flagged
        ])
        if len(flagged_deals) > MAX_FLAGGED_DISPLAY:
            remaining = len(flagged_deals) - MAX_FLAGGED_DISPLAY
            flagged_str += f"\n_... and {remaining} more flagged deal{'s' if remaining != 1 else ''}_"
    else:
        flagged_str = "_No flagged deals — looking good!_"

    # Build recommendations
    if recommendations:
        rec_str = "\n".join([f"{i+1}. {r}" for i, r in enumerate(recommendations)])
    else:
        rec_str = "_No specific recommendations — your pipeline looks healthy_"

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "Pipeline Health Digest", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"📊 Pipeline snapshot as of {timestamp()} · Data from HubSpot CRM"}
            ]
        },

        # Top-line metrics in 2-column grid
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Total Pipeline:*\n{format_currency(total_value)}"},
                {"type": "mrkdwn", "text": f"*Open Deals:*\n{deal_count}"},
                {"type": "mrkdwn", "text": f"*Weighted Forecast:*\n{format_currency(weighted_forecast)}"},
                {"type": "mrkdwn", "text": f"*Flagged:*\n{len(flagged_deals)} deals"},
            ]
        },

        {"type": "divider"},

        # By stage
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*By Stage:*\n{stage_str}"}
        },

        {"type": "divider"},

        # Flagged deals
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Flagged Deals:*\n{flagged_str}"}
        },

        {"type": "divider"},

        # Recommendations
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Recommended Actions This Week:*\n{rec_str}"}
        },

        # Action buttons (values must be non-empty for Slack)
        {
            "type": "actions",
            "elements": [
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "View All Flagged Deals", "emoji": True},
                    "action_id": "view_all_flagged_deals",
                    "value": "all_flagged",
                },
                {
                    "type": "button",
                    "text": {"type": "plain_text", "text": "Refresh Pipeline", "emoji": True},
                    "action_id": "refresh_pipeline",
                    "value": "refresh",
                },
            ]
        },

        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Generated by SalesCoach AI • HubSpot + BigQuery • {timestamp()}"}
            ]
        },
    ]

    # Rich fallback for screen readers
    stage_summary = ", ".join([f"{stage}: {count} deals ({format_currency(value)})" for stage, count, value in deals_by_stage[:4]]) if deals_by_stage else "No deals"
    flagged_summary = ", ".join([d.get('name', 'Unknown') for d in flagged_deals[:3]]) if flagged_deals else "None"
    fallback = f"Pipeline Health Digest. Total: {format_currency(total_value)}, {deal_count} deals, {len(flagged_deals)} flagged. By stage: {stage_summary}. Flagged deals: {flagged_summary}."
    return blocks, fallback


def format_flagged_deals_summary(flagged_deals: list) -> tuple[list, str]:
    """Format a summary view of all flagged deals with deep dive buttons.

    Args:
        flagged_deals: List of dicts with 'id', 'name', 'flag', 'reason'

    Returns:
        tuple: (blocks, fallback_text)
    """
    import math
    MAX_DISPLAY = 12  # Slack allows max 50 blocks; each deal uses ~2 blocks

    flag_emoji = {"stale": "⏰", "overdue": "🚨", "at_risk": "⚠️"}

    # Sort: overdue first (most urgent), then stale
    sorted_deals = sorted(
        flagged_deals,
        key=lambda d: (0 if d.get('flag') == 'overdue' else 1, d.get('name', ''))
    )

    displayed = sorted_deals[:MAX_DISPLAY]
    remaining = len(sorted_deals) - MAX_DISPLAY

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "Flagged Deals Overview", "emoji": True}
        },
        {
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"🚩 {len(flagged_deals)} deal{'s' if len(flagged_deals) != 1 else ''} need{'s' if len(flagged_deals) != 1 else ''} your attention · {timestamp()}"}
            ]
        },
    ]

    # Add each displayed deal as a section with a deep dive button
    for i, deal in enumerate(displayed):
        flag_type = deal.get('flag', 'at_risk')
        emoji = flag_emoji.get(flag_type, '⚠️')
        deal_name = deal.get('name', 'Unknown')
        reason = deal.get('reason', 'Flagged')

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"{emoji} *{deal_name}*\n{reason}"
            },
            "accessory": {
                "type": "button",
                "text": {"type": "plain_text", "text": "Deep dive", "emoji": True},
                "action_id": "drill_flagged_deal",
                "value": deal.get("id") or deal_name,
            },
        })

    # Add note about remaining deals
    if remaining > 0:
        blocks.append({
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"_+ {remaining} more flagged deal(s) — prioritize overdue deals above_"}
            ]
        })

    # Action buttons
    blocks.append({
        "type": "actions",
        "elements": [
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "Back to Pipeline", "emoji": True},
                "action_id": "back_to_pipeline",
                "value": "back",
            },
        ]
    })

    # Fallback text
    flagged_summary = ", ".join([d.get('name', 'Unknown') for d in displayed[:5]])
    if remaining > 0:
        flagged_summary += f" (+ {remaining} more)"
    fallback = f"Flagged Deals Overview. {len(flagged_deals)} deals: {flagged_summary}."
    return blocks, fallback
