"""
Transcript-to-Coaching Pipeline
================================
Analyzes sales call transcripts and generates coaching scripts
that get indexed into the RAG store for coaching commands.

Usage:
    python scripts/analyze_transcripts.py                    # Analyze all transcripts
    python scripts/analyze_transcripts.py --file discovery_call_novatech_2026-02-18.md
    python scripts/analyze_transcripts.py --skip-existing    # Skip already analyzed

Prerequisites:
    - OPENROUTER_API_KEY env var set
    - Transcripts in data/mock_crm/call_transcripts/

After running:
    - Re-index: python scripts/index_playbooks.py
"""

import os
import sys
import json
import glob
import argparse
from datetime import datetime

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from llm_factory import get_llm
from langchain_core.messages import SystemMessage, HumanMessage


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRANSCRIPTS_DIR = os.path.join(BASE_DIR, "data", "mock_crm", "call_transcripts")
OUTPUT_DIR = os.path.join(BASE_DIR, "data", "playbooks", "coaching_from_transcripts")
MANIFEST_FILE = os.path.join(OUTPUT_DIR, "analysis_manifest.json")

os.makedirs(OUTPUT_DIR, exist_ok=True)

ANALYSIS_PROMPT = """You are an expert sales coach analyzing a real sales call transcript.

TRANSCRIPT:
{transcript}

Analyze this call and generate a structured coaching script. Extract EVERY coachable moment.

Respond in EXACTLY this format (do NOT deviate):

CALL_SUMMARY:
[2-3 sentence summary of the call: who, what company, what stage, outcome]

CALL_TYPE: [discovery|demo|negotiation|cold_call|follow_up|renewal|upsell]
DIFFICULTY: [easy|medium|hard]
OVERALL_SCORE: [1-10]
REP_NAME: [name of the sales rep]
BUYER_NAME: [name of the buyer]
BUYER_TITLE: [title of the buyer]
COMPANY: [company name]

SKILLS_DEMONSTRATED:
- [Skill 1]: [specific example from the call with timestamp]
- [Skill 2]: [specific example from the call with timestamp]
- [Skill 3]: [specific example from the call with timestamp]

MISSED_OPPORTUNITIES:
- [Opportunity 1]: [what the rep should have done, with the buyer's statement that created the opening]
- [Opportunity 2]: [what the rep should have done]
- [Opportunity 3]: [what the rep should have done]

TECHNIQUE_USAGE:
- [Technique name, e.g., "SPIN Implication Question"]: [USED/MISSED] — [context]
- [Technique name]: [USED/MISSED] — [context]

BEST_MOMENT:
[Timestamp]: [Quote from the rep that was excellent] — [Why it was effective]

WORST_MOMENT:
[Timestamp]: [Quote from the rep or moment that was poor] — [What should have been said instead]

COACHING_SCRIPT:
[Write a 3-4 paragraph coaching narrative that could be used to train other reps.
Include: what made this call effective or ineffective, the key learning moments,
and specific techniques that were used or should have been used.
Write as if you are telling a coaching story: "In this call, the rep opened by...
Notice how they... A better approach would have been..."]

ROLEPLAY_SCENARIO:
[Based on this call, describe a roleplay scenario that would help a rep practice
the skills needed. Include the buyer persona, their hidden objections, and what
a successful roleplay looks like.]

TAGS: [comma-separated tags, e.g., discovery, SPIN, pricing_objection, CTO, mid_market]
"""


def load_manifest():
    """Load the analysis manifest (tracks which files have been analyzed)."""
    if os.path.exists(MANIFEST_FILE):
        with open(MANIFEST_FILE, "r") as f:
            return json.load(f)
    return {"analyzed": {}, "last_run": None}


def save_manifest(manifest):
    """Save the analysis manifest."""
    manifest["last_run"] = datetime.now().isoformat()
    with open(MANIFEST_FILE, "w") as f:
        json.dump(manifest, f, indent=2)


def analyze_transcript(transcript_path, llm):
    """Analyze a single transcript and return the coaching script."""
    with open(transcript_path, "r") as f:
        transcript = f.read()

    filename = os.path.basename(transcript_path)
    print(f"  Analyzing: {filename} ({len(transcript)} chars)...")

    response = llm.invoke([
        SystemMessage(content="You are an expert sales coach. Analyze transcripts precisely and extract actionable coaching insights."),
        HumanMessage(content=ANALYSIS_PROMPT.format(transcript=transcript)),
    ])

    return response.content


def format_coaching_script(analysis, source_file):
    """Format the LLM analysis into a markdown coaching script."""
    output = f"""# Coaching Script — Generated from: {source_file}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Source:** data/mock_crm/call_transcripts/{source_file}

---

{analysis}

---
*This coaching script was auto-generated by the Transcript-to-Coaching Pipeline.
Source transcript: {source_file}*
"""
    return output


def main():
    parser = argparse.ArgumentParser(description="Analyze call transcripts for coaching insights")
    parser.add_argument("--file", help="Analyze a specific transcript file")
    parser.add_argument("--skip-existing", action="store_true", help="Skip already analyzed transcripts")
    parser.add_argument("--force", action="store_true", help="Re-analyze all transcripts")
    args = parser.parse_args()

    print("=" * 60)
    print("Transcript-to-Coaching Pipeline")
    print("=" * 60)
    print()

    manifest = load_manifest()
    llm = get_llm()

    # Get transcript files
    if args.file:
        files = [os.path.join(TRANSCRIPTS_DIR, args.file)]
        if not os.path.exists(files[0]):
            print(f"Error: File not found: {args.file}")
            return
    else:
        files = sorted(glob.glob(os.path.join(TRANSCRIPTS_DIR, "*.md")))

    if not files:
        print("No transcript files found in", TRANSCRIPTS_DIR)
        return

    print(f"Found {len(files)} transcript(s) to analyze")
    print()

    analyzed_count = 0
    skipped_count = 0

    for filepath in files:
        filename = os.path.basename(filepath)

        # Skip if already analyzed (unless --force)
        if args.skip_existing and not args.force:
            if filename in manifest.get("analyzed", {}):
                print(f"  Skipping (already analyzed): {filename}")
                skipped_count += 1
                continue

        try:
            analysis = analyze_transcript(filepath, llm)

            # Generate output filename
            output_name = f"coaching_{filename}"
            output_path = os.path.join(OUTPUT_DIR, output_name)

            coaching_script = format_coaching_script(analysis, filename)

            with open(output_path, "w") as f:
                f.write(coaching_script)

            print(f"  ✓ Created: {output_name}")

            # Update manifest
            manifest["analyzed"][filename] = {
                "analyzed_at": datetime.now().isoformat(),
                "output_file": output_name,
                "transcript_size": os.path.getsize(filepath),
            }

            analyzed_count += 1

        except Exception as e:
            print(f"  ✗ Error analyzing {filename}: {e}")

    save_manifest(manifest)

    print()
    print(f"Done! Analyzed: {analyzed_count}, Skipped: {skipped_count}")
    print(f"Coaching scripts saved to: {OUTPUT_DIR}")
    print()
    print("Next step: Re-index the RAG store:")
    print("  python scripts/index_playbooks.py")


if __name__ == "__main__":
    main()
